name: "This is the first Action file."

on:
  push:
    branches:
      - main

jobs:
  labels-issue:
    runs-on: ubuntu-latest
    steps:
      name: "Runing echo command."
      run: echo "THIS IS TEST FILLE"
