name: This is the first Action file.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code.
        uses: actions/checkout@v3
      - name: Run echo command.
        run: echo "This is testing......."

